export {Features} from './sections/Features'
export {Main} from './sections/Main'
export {Numbers} from './sections/Numbers'
export {Feedbacks} from './sections/Feedbacks'
export {Companys} from './sections/Companys'
export {CTA} from './sections/CTA'